spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://kim.cwwgyew6ijp4.ap-northeast-2.rds.amazonaws.com:3306/nmsm
    username: banana
    password: a00000000
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 961163244284-sek7s5lhr3ch4ba1ftc1ggk984m28pvp.apps.googleusercontent.com
            client-secret: cv57bNxy0P0NFWfuzpwPsiiL
            scope:
              - email
              - profile
          facebook:
            client-id: 879157686028541
            client-secret: c777164ea7d4b09ac9886f8276b11a84
            scope:
              - email
              - public_profile
          naver:
            client-id: SuIhx_6I3zf9Picsnvk2
            client-secret: UAssfcFklk
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받아 response라는 값으로 리턴
mybatis:
  type-aliases-package: com.example.nmsm.sta.model
  mapper-locations: classpath:mapper/*.xml

