spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3308/nmsm
    username: root
    password: koreait
#TODO : 추후 실제 서비스때 계정 및 패스워드 변경 필요
#TODO : 및 DB에 계정 생성 및 권한 부여 필요
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 961163244284-sek7s5lhr3ch4ba1ftc1ggk984m28pvp.apps.googleusercontent.com
            client-secret: cv57bNxy0P0NFWfuzpwPsiiL
            scope:
              - email
              - profile
          facebook:
            client-id: 879157686028541
            client-secret: c777164ea7d4b09ac9886f8276b11a84
            scope:
              - email
              - public_profile
          naver:
            client-id: SuIhx_6I3zf9Picsnvk2
            client-secret: UAssfcFklk
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받아 response라는 값으로 리턴
